const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const script=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).find(s=>s.includes('function playerCard(p)'));
const id='c8e46ed6-7024-467e-914b-f74b57f20f9c';
const window={addEventListener(){}};
const document={addEventListener(){},getElementById(){return null}};
vm.runInNewContext(script.replace(/\}\)\(\);\s*$/, 'window.cardTest=playerCard;})();'),{window,document,console,setTimeout(){},clearTimeout(){}});
const card=window.cardTest({id,nickname:'renamed',role:'player'});
assert.equal((card.match(/class="atlas-passion-sparkles /g)||[]).length,2);
assert(card.includes('is-top')&&card.includes('is-bottom'));
assert(!card.includes('🎀'));
assert(!window.cardTest({id:'other',nickname:'passion',display_name:'пасс'}).includes('atlas-passion-sparkles'));
const start=script.indexOf('var achPanel='),end=script.indexOf('var statusRows=',start);
const panel=new Function('p','ach','passionPlayerId','esc','fmtDate',script.slice(start,end)+'return achPanel;');
const definition={code:'personal_passion_visca_barca',title:'visca el barça!',description:'спасибо богу что я не мадридиста',personal_user_id:id};
const render=(player,ach)=>panel({id:player},ach,id,s=>String(s),()=> '29.09.2026');
const output=render(id,[{achievements:definition}]);
for(const text of ['is-passion-mythic','МИФИЧЕСКАЯ','visca el barça!','спасибо богу что я не мадридиста','assets/achievements/barcelona.png'])assert(output.includes(text),text);
assert(!render('other',[{achievements:definition}]).includes('visca el barça!'));
assert(render('other',[{achievements:{code:'streak_3',title:'three'}}]).includes('atlas-achievement-shield'));
const image=fs.readFileSync(path.join(__dirname,'../assets/achievements/barcelona.png'));
assert(image.readUInt32BE(16)>=54);assert(image.readUInt32BE(20)>=54);
assert(html.includes('@media(hover:hover) and (pointer:fine)'));
console.log('PASS passion: stable account ID, exclusive sparkles/achievement, existing streak rendering, local PNG with sufficient resolution.');
module.exports={card:window.cardTest,panel:render,definition,id,html};
